version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    commands:
      - "npm install"
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - "npm build"
artifacts:
  files:
    - "**/*"