version: '3.8'

services:
    prod:
        container_name: prod
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/staywise-api-prod
        ports:
            - 3000:3000
            - 9230:9230
        environment:
            - MONGODB_URI=$MONGODB_URI
            - JWT_SECRET=$JWT_SECRET
            - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
            - SENDGRID_API_KEY=$SENDGRID_API_KEY
        expose: 
            - 3000
        networks:
            - nestjs-network
        restart: unless-stopped
    nginx: 
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/staywise-api-nginx
        container_name: nginx
        networks:
            - nestjs-network
        depends_on: 
            - prod
        ports: 
            - "80:80"
networks:
    nestjs-network: